spring.application.name: carbon-client-demo
carbon.client:
  enabled: true
  endpoint: http://localhost:8080/v2/callbacks/a/fd3c35de-ca5f-4442-87aa-17edc67f93d0
  tenant: 1ce8f6f5-4c92-4d9b-a1fb-57971ab9ea6c
  crypto:
    secret: 4XgD98eGyMDejLvA
    iv: ER2gveZeqYYfj6j8
    salt: LXqF4UX4CiAa9mpm
  serialization:
    desensitization: false
    ignore-unknown-properties: false
