name: Release Test

on:
  workflow_dispatch:

jobs:
  dry-release:
    name: Semantic-Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dry branch
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'feat/semver'
            ]
          tag_format: "v${version}"
          extra_plugins: |
            semantic-release-maven

